components:
  font:
    label: Font
    type: select
    options:
      creatable: true
      values: ["Roboto", "Open Sans", "Lato", "Montserrat", "Poppins", "Merriweather", "Raleway", "Oswald", "Playfair Display", "Source Sans Pro", "Nunito", "Quicksand", "Work Sans", "Bebas Neue", "Muli", "Roboto Slab", "Lora", "Josefin Sans", "Droid Serif", "Cabin", "Arimo", "Ubuntu", "Zilla Slab", "Tisa", "Anton", "Fira Sans", "Varela Round", "Crimson Pro", "Spectral", "Exo 2", "Bitter", "Archivo", "Dosis", "PT Sans", "Lobster", "Pacifico", "Dancing Script", "Sacramento", "Tangerine", "Unbounded", "Pangolin", "Bree Serif", "Vollkorn", "Monda", "Be Vietnam", "Karla", "Noto Sans", "Kalam"]
  blocks:
    label: Bloques pros
    type: object
    list:
      collapsible:
        collapsed: true
        summary: "{fields.type} - {fields.title}"
    fields:
      - { name: type, label: Tipo, type: select, options: { values: ["hero", "gallery", "gallery-feature", "text"] } }
      - { name: title, label: Título, type: string }
      - { name: description, label: Texto, type: rich-text }
      - { name: image, label: Imagen, type: image }
      - name: elements
        label: Elementos
        type: object
        list: { collapsible: { collapsed: true, summary: "{fields.title}" } }
        fields:
          - { name: title, label: Título, type: string }
          - { name: description, label: Texto, type: text }
          - { name: image, label: Imagen, type: image }
          - { name: param, label: Link, type: string }
media:
  input: docs/public/media
  output: /media
  categories: ["image"]
content:
  - name: config
    type: file
    label: Configuración
    path: config.md
    fields:
      - { name: title, label: Titulo sitio, type: string }
      - { name: description, label: Description del sitio, type: text }
      - name: nav
        label: Menu de navegación
        type: object
        list: { collapsible: { collapsed: true, summary: "{fields.title}" } }
        fields:
          - { name: title, label: Titulo sección, type: string }
          - name: links
            label: Enlaces
            type: reference
            options: { collection: pages, multiple: true, label: "{title}" }
      - name: theme
        label: Tema visual
        type: object
        fields:
          - { name: bodyFont, label: Tipo de letra del cuerpo (cualquiera de https://fonts.google.com/), component: font }
          - { name: headingFont, label: Tipo de letra de los titulos (cualquiera de https://fonts.google.com/), component: font }
      - name: styles
        label: Estilos y efectos
        type: object
        list: { collapsible: { collapsed: true, summary: "{fields.selector}" } }
        fields:
          - { name: selector, label: "Selector", type: string }
          - { name: cssClass, label: "cssClass", type: string }
          - { name: scroll, label: "scroll", type: boolean }

  - name: pages
    label: Paginas
    type: collection
    path: docs
    view:
      fields: [image, title]
      primary: title
    filename: "{primary}.md"
    exclude: [.vitepress, public]
    fields:
      - { name: title, label: Título, type: string }
      - { name: description, label: Subtitulo, type: string }
      - { name: image, label: Imagen, type: image }
      - { name: body, label: Texto largo, type: rich-text }
      - name: links
        label: Enlaces internos
        type: reference
        options: { collection: pages, multiple: true, label: "{title}" }
      - name: sections
        label: Page Sections
        type: block
        list: true
        blocks:
          - name: hero
            label: Add Hero Section
            component: font
          - name: text
            label: Add Text Block
            fields:
              - name: content
                label: Text Content
                type: rich-text
