components:
  blocks:
    label: Bloques pros
    type: object
    list:
      collapsible:
        collapsed: true
        summary: "{fields.type} - {fields.title}" 
    fields:
      - { name: type, label: Tipo, type: select, options: { values: ['Hero','Galeria','Galeria horizontal','Galeria con buscador','Texto largo','Otros bloques....']} }
      - { name: title, label: Título, type: string }
      - { name: description, label: Texto, type: rich-text }
      - name: elements
        label: Elementos
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.title}" 
        fields:
          - { name: title, label: Título, type: string }
          - { name: description, label: Texto, type: text }
          - { name: image, label: Imagen, type: image }
          - { name: param, label: Link, type: string }
#- { name: section, label: seccion, type: select, options: { values: ['Discernimiento','Sacerdocio','Seminario','Monaguillos','Vida laical y familia','Noviazgo','Vida religiosa y mision', 'Recursos', 'Eventos']} }
media:
  input: media
  output: media
  categories: [ "image" ]
content:
  - name: pages
    label: Paginas
    type: collection
    path: docs
    view:
      fields: [ image, title]
    fields:
      - { name: title, label: Title, type: string }
      - { name: sortTitle, label: Short Title, type: string }
      - { name: description, label: Descripcion corta, type: text }
      - { name: image, label: Cover, type: image }
      - { name: blocks, component: blocks }