components:
  hero: # 'hero' is the component name/key
    label: Hero Section
    type: object
    fields:
      - name: headline
        label: Headline
        type: text
        required: true
      - name: cover
        label: Cover Image
        type: image
  email: # 'email' is the component name/key
    label: Email Address
    type: string
    pattern:
      regex: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
      message: 'This must be a valid email address (e.g. hello@example.com).'
media:
  input: public/assets
  output: /assets
  categories: [ "image" ]
content:
  - name: home
    label: Portada
    type: file
    path: index
    fields:
      - { name: hero, label: Hero, component: hero }
      - { name: title, label: Title, type: string}
      - { name: excerpt, label: Descripcion, type: string }
      - { name: coverImage, label: Cover, type: image }
      - { name: body, label: Body, type: rich-text }
      - name: blocks
        label: Bloques
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.type} - {fields.title}" 
        fields:
          - { name: type, label: Tipo, type: select, options: { values: ['Hero','Galeria','Galeria horizontal','Galeria con buscador','...']} }
          - { name: title, label: Título, type: string }
          #- { name: image, label: Imagen, type: image }
          #- { name: body, label: Texto, type: rich-text }
          - name: elems
            label: Elementos
            type: object
            list:
              collapsible:
                collapsed: true
                summary: "{fields.title}" 
            fields:
              - { name: title, label: Título, type: string }
              - { name: description, label: Texto, type: rich-text }
              - { name: image, label: Imagen, type: image }
              - { name: param, label: Link, type: string }
  - name: section
    label: Secciones
    type: collection
    path: _sections
    view:
      fields: [ coverImage, title]
    fields:
      - { name: title, label: Title, type: string }
      - { name: excerpt, label: Descripcion, type: string }
      - { name: section, label: seccion, type: select, options: { values: ['Discernimiento','Sacerdocio','Seminario','Monaguillos','Vida laical y familia','Noviazgo','Vida religiosa y mision', 'Recursos', 'Eventos']} }
      - { name: coverImage, label: Cover, type: image }
      - { name: body, label: Body, type: rich-text }
  - name: posts
    label: Articulo
    type: collection
    path: _posts
    view:
      fields: [ coverImage, title]
    fields:
      - { name: title, label: Title, type: string }
      - { name: excerpt, label: Descripcion, type: string }
      - { name: section, label: seccion, type: select, options: { values: ['Discernimiento','Sacerdocio','Seminario','Monaguillos','Vida laical y familia','Noviazgo','Vida religiosa y mision', 'Recursos', 'Eventos']} }
      - { name: coverImage, label: Cover, type: image }
      - { name: body, label: Body, type: rich-text }