components:
  blocks:
    label: Bloques pros
    type: object
    list:
      collapsible:
        collapsed: true
        summary: "{fields.type} - {fields.title}"
    fields:
      - { name: type, label: Tipo, type: select, options: { values: ["hero", "gallery", "gallery-feature", "text"] } }
      - { name: title, label: Título, type: string }
      - { name: description, label: Texto, type: rich-text }
      - { name: image, label: Imagen, type: image }
      - name: elements
        label: Elementos
        type: object
        list: { collapsible: { collapsed: true, summary: "{fields.title}" } }
        fields:
          - { name: title, label: Título, type: string }
          - { name: description, label: Texto, type: text }
          - { name: image, label: Imagen, type: image }
          - { name: param, label: Link, type: string }
media:
  input: docs/public/media
  output: /media
  categories: ["image"]
content:
  - name: config
    type: file
    label: Configuración
    path: config.md
    fields:
      - { name: title, label: Titulo sitio, type: string }
      - { name: description, label: Description del sitio, type: text }
      - name: nav
        label: Menu de navegación
        type: object
        list: { collapsible: { collapsed: true, summary: "{fields.title}" } }
        fields:
          - { name: title, label: Titulo sección, type: string }
          - name: links
            label: Enlaces
            type: reference
            options: { collection: pages, multiple: true, label: "{title}" }
      - name: theme
        label: Tema visual
        type: object
        fields:
          - { name: bodyFont, label: Fuente del cuerpo, description: "Nombre de cualquier fuente en https://fonts.google.com/", type: string }
          - { name: headingFont, label: Fuente de los titulos, description: "Nombre de cualquier fuente en https://fonts.google.com/", type: string }
      - name: styles
        label: Estilos y efectos
        type: object
        list: { collapsible: { collapsed: true, summary: "{fields.selector}" } }
        fields:
          - { name: selector, label: "Selector", type: string }
          - { name: cssClass, label: "cssClass", type: string }
          - { name: scroll, label: "scroll", type: boolean }

  - name: pages
    label: Paginas
    type: collection
    path: docs
    view:
      fields: [image, title]
      primary: title
    filename: "{primary}.md"
    exclude: [.vitepress, public]
    fields:
      - { name: title, label: Título, type: string }
      - { name: description, label: Subtitulo, type: string }
      - { name: image, label: Imagen, type: image }
      - { name: body, label: Texto largo, type: rich-text }
      - name: links
        label: Enlaces internos
        type: reference
        options: { collection: pages, multiple: true, label: "{title}" }
