media:
  input: public/assets
  output: /assets
  categories: [ "image" ]
content:
  - name: posts
    label: Articulo
    type: collection
    path: _posts
    view:
      fields: [ coverImage, title, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: excerpt, label: Descripcion, type: string }
      - { name: section, label: seccion, type: string }
      - { name: coverImage, label: Cover image, type: image }
      - { name: body, label: Body, type: rich-text }