components:
  blocks:
    label: Bloques pros
    type: object
    list:
      collapsible:
        collapsed: true
        summary: "{fields.type} - {fields.title}"
    fields:
      - { name: type, label: Tipo, type: select, options: { values: ["hero", "gallery", "gallery-feature", "text"] } }
      - { name: title, label: Título, type: string }
      - { name: description, label: Texto, type: rich-text }
      - { name: image, label: Imagen, type: image }
      - name: elements
        label: Elementos
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.title}"
        fields:
          - { name: title, label: Título, type: string }
          - { name: description, label: Texto, type: text }
          - { name: image, label: Imagen, type: image }
          - { name: param, label: Link, type: string }
media:
  input: docs/public/media
  output: /media
  categories: ["image"]
content:
  - name: config
    type: file
    label: Configuración
    path: config.md
    fields:
      - name: theme
        type: string
      - name: nav
        label: Navegacion
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.title}"
        fields:
          - { name: title, label: Titulo sección, type: string }
          - name: links
            label: Enlaces
            type: reference
            options:
              collection: pages
              multiple: true
              search: "title,description"
              label: "{title}"
              image: "{image}"
  - name: pages
    label: Paginas
    type: collection
    path: docs
    view:
      fields: [image, title]
      primary: title
    filename: "{primary}.md"
    exclude: [.vitepress, public]
    fields:
      - { name: title, label: Título, type: string }
      - { name: subtitle, label: Subtitulo, type: string }
      - { name: description, label: Texto largo, type: rich-text }
      - { name: image, label: Imagen, type: image }
      - name: links
        label: Enlaces internos
        type: reference
        options:
          collection: pages
          multiple: true
          label: "{title}"
      - { name: blocks, component: blocks }
