media:
  input: public/assets
  output: /assets
  categories: [ "image" ]
content:
  - name: home
    label: Portada
    type: file
    path: index
    fields:
      - { name: title, label: Title, type: string}
      - { name: excerpt, label: Descripcion, type: string }
      - { name: coverImage, label: Cover image, type: image }
      - { name: body, label: Body, type: rich-text }
  - name: section
    label: Secciones
    type: collection
    path: _sections
    view:
      fields: [ coverImage, title, date ]
    fields:
      - { name: title, label: Title, type: string }
      - { name: excerpt, label: Descripcion, type: string }
      - { name: section, label: seccion, type: select, options: { values: ['Discernimiento','Sacerdocio','Seminario','Monaguillos','Vida laical y familia','Noviazgo','Vida religiosa y mision', 'Recursos', 'Eventos']} }
      - { name: coverImage, label: Cover image, type: image }
      - { name: body, label: Body, type: rich-text }
  - name: posts
    label: Articulo
    type: collection
    path: _posts
    view:
      fields: [ coverImage, title, date ]
    fields:
      - { name: title, label: Title, type: string }
      - { name: excerpt, label: Descripcion, type: string }
      - { name: section, label: seccion, type: select, options: { values: ['Discernimiento','Sacerdocio','Seminario','Monaguillos','Vida laical y familia','Noviazgo','Vida religiosa y mision', 'Recursos', 'Eventos']} }
      - { name: coverImage, label: Cover image, type: image }
      - { name: body, label: Body, type: rich-text }